version: "2.1"

services:
  mysql:
    image: mysql:8.0.14
    container_name: mysql
    networks:
      - my_net
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=helloroot
      - MYSQL_DATABASE=masterdb
      - MYSQL_USER=hello
      - MYSQL_PASSWORD=hello
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    ports:
      - 3306:3306

networks:
  my_net:
    driver: bridge
